export interface ReportData {
  projectName?: string;
  totalDocuments: number;
  topics: Array<{
    id: number;
    name: string; // Top 3 words joined
    size: number;
    words: Array<{ word: string; score: number }>;
    summary?: string;
    analytics?: any;
  }>;
  executionTimeMs?: number;
  // Optional detailed data for plots
  umap?: number[][];
  labels?: number[];
  similarityMatrix?: number[][];
  topicLabels?: string[];
  uniqueClasses?: number[];
}

export interface HTMLReportOptions {
  includePlotlyScript?: boolean; // Inject plotly CDN script
  externalDataUrl?: string; // If set, the HTML will attempt to fetch data from this URL instead of embedding it
}

export class ReportGenerator {
  /**
   * Generates a structured Markdown report from the pipeline results.
   */
  static generateMarkdown(data: ReportData): string {
    let md = `# Topic Modeling Analysis Report\n\n`;

    if (data.projectName) {
      md += `**Project:** ${data.projectName}\n`;
    }
    md += `**Total Documents Processed:** ${data.totalDocuments}\n`;
    md += `**Total Topics Discovered:** ${data.topics.length}\n`;

    if (data.executionTimeMs) {
      md += `**Execution Time:** ${(data.executionTimeMs / 1000).toFixed(2)} seconds\n`;
    }

    md += `\n---\n\n## Discovered Topics\n\n`;

    // Sort topics by size descending, but keep noise (-1) at the end if it exists
    const sortedTopics = [...data.topics].sort((a, b) => {
        if (a.id === -1) return 1;
        if (b.id === -1) return -1;
        return b.size - a.size;
    });

    for (const topic of sortedTopics) {
      const isNoise = topic.id === -1;
      const title = isNoise ? `Topic -1: Outlier / Noise` : `Topic ${topic.id}: ${topic.name}`;

      md += `### ${title}\n`;
      md += `- **Document Count:** ${topic.size} (${((topic.size / data.totalDocuments) * 100).toFixed(1)}% of corpus)\n`;

      if (topic.summary) {
          md += `- **Summary:** ${topic.summary}\n`;
      }

      if (topic.analytics) {
          const sentimentStr = topic.analytics.sentiment > 0 ? 'Positive' : topic.analytics.sentiment < 0 ? 'Negative' : 'Neutral';
          md += `- **General Sentiment:** ${sentimentStr} (${topic.analytics.sentiment.toFixed(2)})\n`;
          if (topic.analytics.entities.dates.length > 0) md += `- **Extracted Dates:** ${topic.analytics.entities.dates.slice(0,5).join(', ')}\n`;
          if (topic.analytics.entities.money.length > 0) md += `- **Extracted Money/Values:** ${topic.analytics.entities.money.slice(0,5).join(', ')}\n`;
          if (topic.analytics.entities.emails.length > 0) md += `- **Extracted Emails:** ${topic.analytics.entities.emails.slice(0,5).join(', ')}\n`;
      }

      md += `- **Top Keywords (c-TF-IDF):**\n`;
      for (const w of topic.words.slice(0, 10)) {
          md += `  - ${w.word} (${w.score.toFixed(4)})\n`;
      }
      md += `\n`;
    }

    return md;
  }

  /**
   * Generates a professional HTML report featuring interactive Plotly visualizations.
   * Can be self-contained or reference external assets based on options.
   */
  static generateHTML(data: ReportData, options: HTMLReportOptions = {}): string {
    const includePlotlyScript = options.includePlotlyScript !== false;
    const markdown = this.generateMarkdown(data);

    // Markdown to HTML conversion
    let htmlContent = markdown
        .replace(/^# (.*$)/gim, '<h1 class="text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight mb-2">$1</h1><p class="text-lg text-slate-500 dark:text-slate-400 mb-8 pb-4 border-b dark:border-slate-700">Generated by Edge-Native Topic Modeler</p>')
        .replace(/^## (.*$)/gim, '<h2 class="text-3xl font-bold text-slate-800 dark:text-slate-100 mt-12 mb-6 border-b dark:border-slate-700 pb-2">$1</h2>')
        .replace(/^### (.*$)/gim, '<h3 class="text-2xl font-semibold text-slate-800 dark:text-slate-100 mt-8 mb-4">$1</h3>')
        .replace(/^\*\*([^]*?)\*\*(.*)/gim, '<strong class="text-slate-900 dark:text-white">$1</strong><span class="text-slate-600 dark:text-slate-300">$2</span><br>')
        .replace(/^- \*\*([^]*?)\*\* (.*)/gim, '<li class="mb-2"><strong class="text-slate-800 dark:text-slate-200">$1</strong> <span class="text-slate-600 dark:text-slate-300">$2</span></li>')
        .replace(/^- \*\*([^]*?)\*\*$/gim, '<p class="font-semibold text-slate-800 dark:text-slate-200 mt-4 mb-2">$1</p><ul class="list-disc pl-6 mb-6">')
        .replace(/^  - (.*)/gim, '<li class="text-slate-600 dark:text-slate-400">$1</li>')
        .replace(/---/gim, '')
        .replace(/\n\n/gim, '</p><p class="mb-4">')
        .replace(/<\/ul><\/p><p class="mb-4">/gim, '</ul>')
        .replace(/<\/p><p class="mb-4"><li/gim, '<li');

    // Prepare JSON payload for the plots
    let plotDataScript = '';

    if (options.externalDataUrl) {
        // Load data via script tag to avoid local file:// CORS restrictions
        plotDataScript = `
        <script src="${options.externalDataUrl}"></script>
        `;
    } else {
        plotDataScript = `
        <script>
            window.reportData = ${JSON.stringify({
                topics: data.topics.sort((a,b) => b.size - a.size), // Keep noise wherever for charts, just sort by size
                umap: data.umap || [],
                labels: data.labels || [],
                similarityMatrix: data.similarityMatrix || [],
                topicLabels: data.topicLabels || [],
                uniqueClasses: data.uniqueClasses || []
            })};
        </script>
        `;
    }

    // Interactive visualization script using Plotly
    const vizScript = `
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                const data = window.reportData;
                if (!data || !data.umap || data.umap.length === 0) return;

                const isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;
                const fontColor = isDarkMode ? '#e2e8f0' : '#334155';
                const gridColor = isDarkMode ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)';

                // 1. Render Intertopic Distance Map (UMAP Projection)
                const x = data.umap.map(c => c[0]);
                const y = data.umap.map(c => c[1]);

                // Color mapping: generate distinct colors for distinct topic IDs
                const uniqueLabels = [...new Set(data.labels)];
                const colors = data.labels.map(label => {
                   if (label === -1) return '#cbd5e1'; // noise is gray
                   return \`hsl(\${(Number(label) * 137.508) % 360}, 70%, 50%)\`;
                });

                const hoverText = data.labels.map(label => {
                    if (label === -1) return "Noise";
                    const topic = data.topics.find(t => t.id === label);
                    return topic ? \`Topic \${topic.id}: \${topic.name}\` : \`Topic \${label}\`;
                });

                Plotly.newPlot('umap-plot', [{
                    x: x,
                    y: y,
                    mode: 'markers',
                    type: 'scatter',
                    text: hoverText,
                    hoverinfo: 'text',
                    marker: {
                        size: 10,
                        color: colors,
                        opacity: 0.8,
                        line: { width: 0.5, color: isDarkMode ? '#1e293b' : 'white' }
                    }
                }], {
                    title: 'Document Clusters (UMAP Projection)',
                    hovermode: 'closest',
                    paper_bgcolor: 'transparent',
                    plot_bgcolor: 'transparent',
                    font: { color: fontColor },
                    xaxis: { showgrid: true, zeroline: false, showticklabels: false, gridcolor: gridColor },
                    yaxis: { showgrid: true, zeroline: false, showticklabels: false, gridcolor: gridColor },
                    margin: { l: 20, r: 20, t: 40, b: 20 }
                }, { responsive: true, displayModeBar: false });

                // 2. Render Topic Bar Charts
                // Get top 6 topics (excluding noise)
                const topTopics = data.topics.filter(t => t.id !== -1).slice(0, 6);

                const barChartData = topTopics.map((topic, i) => {
                    const topWords = topic.words.slice(0, 10).reverse();
                    return {
                        type: 'bar',
                        x: topWords.map(w => w.score),
                        y: topWords.map(w => w.word),
                        orientation: 'h',
                        name: \`Topic \${topic.id}\`,
                        xaxis: 'x' + (i === 0 ? '' : i + 1),
                        yaxis: 'y' + (i === 0 ? '' : i + 1),
                        marker: {
                            color: \`hsl(\${(topic.id * 137.508) % 360}, 70%, 50%)\`
                        }
                    };
                });

                // Layout grid for bar charts
                const barLayout = {
                    title: 'Top Keyword Scores (c-TF-IDF)',
                    grid: {rows: Math.max(1, Math.ceil(topTopics.length / 2)), columns: Math.min(2, topTopics.length || 1), pattern: 'independent'},
                    height: Math.ceil(topTopics.length / 2) * 300,
                    showlegend: false,
                    paper_bgcolor: 'transparent',
                    plot_bgcolor: 'transparent',
                    font: { color: fontColor },
                    margin: { l: 100, r: 20, t: 50, b: 40 }
                };

                // Format axes dynamically based on how many subplots we generated
                for(let i=0; i < topTopics.length; i++) {
                   const suffix = i === 0 ? '' : i+1;
                   barLayout['xaxis' + suffix] = { showticklabels: false, showgrid: false, gridcolor: gridColor, zerolinecolor: gridColor };
                   barLayout['yaxis' + suffix] = { automargin: true, gridcolor: gridColor };
                }

                if (topTopics.length > 0) {
                    document.getElementById('barchart-container').style.display = 'block';
                    Plotly.newPlot('barchart-plot', barChartData, barLayout, { responsive: true, displayModeBar: false });
                }

                // 3. Render Topic Distribution Pie Chart
                const allTopics = data.topics.sort((a,b) => b.size - a.size);
                if (allTopics.length > 0) {
                    const pieColors = allTopics.map(topic => {
                        if (topic.id === -1) return '#cbd5e1';
                        return \`hsl(\${(topic.id * 137.508) % 360}, 70%, 50%)\`;
                    });

                    const pieData = [{
                        values: allTopics.map(t => t.size),
                        labels: allTopics.map(t => t.id === -1 ? 'Noise (-1)' : \`Topic \${t.id}: \${t.name.split(',')[0]}\`),
                        type: 'pie',
                        marker: { colors: pieColors },
                        hoverinfo: 'label+percent+value'
                    }];
                    const pieLayout = {
                        title: 'Topic Distribution',
                        margin: { l: 20, r: 20, t: 50, b: 20 },
                        paper_bgcolor: 'transparent',
                        plot_bgcolor: 'transparent',
                        font: { color: fontColor }
                    };
                    document.getElementById('pie-container').style.display = 'block';
                    Plotly.newPlot('pie-plot', pieData, pieLayout, { responsive: true, displayModeBar: false });
                }

                // 4. Render Similarity Heatmap
                if (data.similarityMatrix && data.similarityMatrix.length > 0) {
                    const heatmapData = [{
                        z: data.similarityMatrix,
                        x: data.topicLabels.map((_, i) => 'T' + i), // Short labels for X axis
                        y: data.topicLabels, // Full labels for Y axis
                        type: 'heatmap',
                        colorscale: 'Blues',
                        showscale: true,
                        hoverongaps: false,
                        zmin: 0,
                        zmax: 1
                    }];
                    const heatmapLayout = {
                        title: 'Topic Similarity Heatmap',
                        autosize: true,
                        margin: { l: 150, r: 20, t: 50, b: 50 },
                        paper_bgcolor: 'transparent',
                        plot_bgcolor: 'transparent',
                        font: { color: fontColor },
                        xaxis: {
                            tickangle: -45,
                            gridcolor: gridColor
                        },
                        yaxis: {
                            gridcolor: gridColor
                        }
                    };
                    document.getElementById('heatmap-container').style.display = 'block';
                    Plotly.newPlot('heatmap-plot', heatmapData, heatmapLayout, { responsive: true, displayModeBar: false });
                }

            });
        </script>
    `;

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edge-Native Topic Modeling Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            darkMode: 'media',
        }
    </script>
    ${includePlotlyScript ? '<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>' : '<!-- Plotly should be loaded by the parent environment -->'}
    ${plotDataScript}
    <style>
        body { font-family: 'Inter', system-ui, -apple-system, sans-serif; }
        .viz-card { border-radius: 0.75rem; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06); padding: 1.5rem; margin-top: 2rem; margin-bottom: 2rem; border-width: 1px; }
        .content-card { border-radius: 0.75rem; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06); padding: 3rem; border-width: 1px; }
    </style>
</head>
<body class="text-slate-700 dark:text-slate-300 bg-slate-100 dark:bg-slate-900 antialiased">
    <div class="max-w-5xl mx-auto px-4 py-8">

        <div class="content-card bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 mb-8">
            ${htmlContent.split('<h2 class="text-3xl font-bold text-slate-800 dark:text-slate-100 mt-12 mb-6 border-b dark:border-slate-700 pb-2">Discovered Topics</h2>')[0]}
        </div>

        <!-- Visualizations -->
        ${data.umap && data.umap.length > 0 ? `
        <div class="viz-card bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700">
            <h3 class="text-xl font-bold text-slate-800 dark:text-slate-200 mb-2">Document Clusters Map</h3>
            <p class="text-sm text-slate-500 dark:text-slate-400 mb-4">Interactive 2D projection of the corpus using UMAP dimensionality reduction.</p>
            <div id="umap-plot" style="width:100%; min-height:400px; height:60vh;"></div>
        </div>

        <div class="viz-card bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700" id="barchart-container" style="display:none;">
            <div id="barchart-plot" style="width:100%;"></div>
        </div>
        ` : ''}


        <div class="viz-card bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700" id="pie-container" style="display:none;">
            <h3 class="text-xl font-bold text-slate-800 dark:text-slate-200 mb-2">Topic Sizes</h3>
            <div id="pie-plot" style="width:100%; min-height:400px; height:50vh;"></div>
        </div>

        <div class="viz-card bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700" id="heatmap-container" style="display:none;">
            <h3 class="text-xl font-bold text-slate-800 dark:text-slate-200 mb-2">Topic Similarity</h3>
            <p class="text-sm text-slate-500 dark:text-slate-400 mb-4">Cosine correlation between c-TF-IDF topic representations.</p>
            <div id="heatmap-plot" style="width:100%; min-height:400px; height:60vh;"></div>
        </div>


        <div class="content-card bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700">
            <h2 class="text-3xl font-bold text-slate-800 dark:text-slate-100 mb-6 border-b dark:border-slate-700 pb-2">Topic Details</h2>
            ${htmlContent.split('<h2 class="text-3xl font-bold text-slate-800 dark:text-slate-100 mt-12 mb-6 border-b dark:border-slate-700 pb-2">Discovered Topics</h2>')[1] || ''}
        </div>

    </div>
    ${vizScript}
</body>
</html>`;
  }
}
